/* 
**  mod_konoha.c -- Apache sample konoha module
**  [Autogenerated via ``apxs -n konoha -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_konoha.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /konoha in as follows:
**
**    #   httpd.conf
**    LoadModule konoha_module modules/mod_konoha.so
**    <Location /konoha>
**    SetHandler konoha
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /konoha and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/konoha 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_konoha.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include <konoha1.h>

#define PATHSIZE 1024

module AP_MODULE_DECLARE_DATA konoha_module;

/* utility of read from POST body */
#if 0
static int util_read(request_rec *r, const char **rbuf)
{
    int rc;

    if (r->method_number != M_POST) {
        return DECLINED;
    }

    if ((rc = ap_setup_client_block(r, REQUEST_CHUNKED_ERROR)) != OK) {
        return rc;
    }

    if (ap_should_client_block(r)) {
        char argsbuffer[HUGE_STRING_LEN];
        int rsize, len_read, rpos=0;
        long length = r->remaining;
        *rbuf = apr_pcalloc(r->pool, length + 1);

        while ((len_read = ap_get_client_block(r, argsbuffer,
                        sizeof(argsbuffer))) > 0 ) {
            if ((rpos + len_read) > length) {
                rsize = length - rpos;
            }
            else {
                rsize = len_read;
            }
            memcpy((char *)*rbuf + rpos, argsbuffer, rsize);
            rpos += rsize;
        }
    }

    return rc;
}
#endif

#if 0
/* utility of read from POST body form */
static int read_post(request_rec *r, apr_table_t **tab)
{
    const char *data;
    const char *key, *val, *type;
    int rc = OK;

    if (r->method_number != M_POST) {
        return DECLINED;
    }

    type = apr_table_get(r->headers_in, "Content-Type");
    if (strcasecmp(type, "application/x-www-form-urlencoded") != 0) {
        return DECLINED;
    }

    if ((rc = util_read(r, &data)) != OK) {
        return rc;
    }

    if (*tab) {
        apr_table_clear(*tab);
    }
    else {
        *tab = apr_table_make(r->pool, 8);
    }

    while (*data && (val = ap_getword(r->pool, &data, '&'))) {
        key = ap_getword(r->pool, &val, '=');

        ap_unescape_url((char *)key);
        ap_unescape_url((char *)val);

        apr_table_merge(*tab, key, val);
    }

    return OK;
}
#endif

/* konoha handler */
static int konoha_handler(request_rec *r)
{
    if (strcmp(r->handler, "konoha")) {
        return DECLINED;
    }
    r->content_type = "application/json";
    r->content_encoding = "utf-8";

    char *handler = (char *)ap_get_module_config(r->per_dir_config, &konoha_module);

    ap_rprintf(r, "KonohaHandler=\"%s\"\n", handler);
    return OK;
}

/* copy .conf arguments */
static const char *set_handler(cmd_parms *cmd, void *vp, const char *arg)
{
    (void)cmd;
    char *hdr = (char *)vp;
    strncpy(hdr, arg, sizeof(hdr));
    return NULL;
}

/* configure konoha create dir */
static void *konoha_cdir_cfg(apr_pool_t *pool, char *arg)
{
    (void)arg;
    char *hdr;
    hdr = (char *)apr_palloc(pool, sizeof(char) * PATHSIZE);
    return (void *)hdr;
}

/* konoha commands */
static const command_rec konoha_cmds[] = {
    AP_INIT_TAKE1("KonohaHandler",
        set_handler,
        NULL,
        OR_ALL,
        "set konoha handler"),
    { NULL, {NULL}, NULL, 0, RAW_ARGS, NULL }
};

/* konoha register hooks */
static void konoha_register_hooks(apr_pool_t *p)
{
    (void)p;
    ap_hook_handler(konoha_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA konoha_module = {
    STANDARD20_MODULE_STUFF,
    konoha_cdir_cfg,       /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    konoha_cmds,           /* table of config file commands       */
    konoha_register_hooks  /* register hooks                      */
};

